name: Auto Update Toolforge

on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE" # /home/runner/work/svg_translate_web/svg_translate_web # ls -al

      - name: Copy files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "./"
          target: "~/svg_tr_repo_tmp"
          rm: true

      - name: Deploy on Toolforge
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            become copy-svg-langs bash -lc "
              rm -rf ~/svg_tr_repo &&
              cp -r /mnt/nfs/labstore-secondary-tools-home/${{ secrets.USERNAME }}/svg_tr_repo_tmp ~/svg_tr_repo &&
              cp -r ~/svg_tr_repo/web_sh/* ~/web_sh &&
              chmod -R 770 ~/web_sh &&
              toolforge-jobs run update --image python3.13 --command ~/web_sh/update.sh --wait &&
              rm -rf ~/svg_tr_repo &&
              echo \"Updated on: $(date '+%Y-%m-%d %H:%M:%S')\" > ~/update_from_github &&
              toolforge-jobs run pipup --image python3.13 --command ~/web_sh/pip.sh --wait &&
              toolforge-webservice python3.13 stop &&
              toolforge-webservice python3.13 start &&
              echo ''
            "
            rm -rf svg_tr_repo_tmp
